image: node:latest

stages:
  - deploy

## deploy to staging server
deploy_staging:
  stage: deploy
  environment:
    name: Staging
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./functions/node_modules
  before_script:
    - npm install -g firebase-tools
    - cd ./functions
    - npm install
  script:
    - firebase use $FIREBASE_REPO --token $FIREBASE_TOKEN
    - firebase functions:config:set qbot.url=$QBOT_API_URL qbot.access_token=$QBOT_ACCESS_TOKEN qbot.webhook_enpoint=$QBOT_WEBHOOK_ENDPOINT
    - firebase deploy --only functions --token $FIREBASE_TOKEN

## deploy to production server
deploy_production:
  stage: deploy
  environment:
    name: Production
  only:
    - tags
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./functions/node_modules
  before_script:
    - npm install -g firebase-tools
    - cd ./functions
    - npm install
  script:
    - firebase use $FIREBASE_REPO --token $FIREBASE_TOKEN
    - firebase functions:config:set qbot.url=$QBOT_API_URL qbot.access_token=$QBOT_ACCESS_TOKEN qbot.webhook_enpoint=$QBOT_WEBHOOK_ENDPOINT
    - firebase deploy --only functions --token $FIREBASE_TOKEN
